### ISSUE TITLE
`disk_info` object contains insufficient information after update to 3.0.4

### ISSUE THREAD

**Issue by GalaxyGorilla** [hashicorp/vagrant-vmware-desktop#157]
### Vagrant version

Vagrant 2.4.3

### Vagrant VMware plugin version

This issue is about a change from 3.0.3 --> 3.0.4

### Vagrant VMware utility version

1.0.23

### Host operating system

MacOS 15.4

### Description

With the update of the plugin to 3.0.4 I get the following error:

```
% vagrant reload
==> default: Attempting graceful shutdown of VM...
==> default: Checking if box 'uwbbi/bionic-arm64' version '1.0.1' is up to date...
==> default: Verifying vmnet devices are healthy...
==> default: Preparing network adapters...
/Users/sascha/.vagrant.d/gems/3.3.6/gems/vagrant-vmware-desktop-3.0.4/lib/vagrant-vmware-desktop/cap/disk.rb:118:in `block in get_disk': undefined method `[]' for nil (NoMethodError)

              return disk_info if disk_info["present"].to_s.upcase == "TRUE"
                                           ^^^^^^^^^^^
	from /Users/sascha/.vagrant.d/gems/3.3.6/gems/vagrant-vmware-desktop-3.0.4/lib/vagrant-vmware-desktop/cap/disk.rb:115:in `each'
	from /Users/sascha/.vagrant.d/gems/3.3.6/gems/vagrant-vmware-desktop-3.0.4/lib/vagrant-vmware-desktop/cap/disk.rb:115:in `get_disk'
[...]
```

I forced the version back to 3.0.3 and now everything is working fine again. There seems to be trouble with the generation of the disk info object. I can see that there was work done on this for the patch release.

**Comment by chrisroberts** [comment]
Hi there. Thanks for this report! You are correct, there was work done in #151 around this for the upcoming patch release. This specific issue being addressed [here](https://github.com/hashicorp/vagrant-vmware-desktop/pull/151/files#diff-3e6f1f210ef6b55b2f05bf98a618fb8682b9773a5dfd749806d4790c0cb2afbfR117). 

As this issue has been fixed I'm going to close this now.

Cheers!
